config/routes.rb
Rails.application.routes.draw do
  root to: "goouts#index"
  devise_for :users
  resources :outs, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/out.rb
class Out < ApplicationRecord
  validate :get_out
  validate :go_home
  validate :receipt_id
  validate :return_id
  validates :user_id,   presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
  end

  has_many :outs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'nakazato' && password == '8629'
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/goouts_controller.rb
class GooutsController < ApplicationController
  before_action :manji, except: :index

  def index
  end

end

app/controllers/outs_controller.rb
class OutsController < ApplicationController

  def index
    @outs = Out.find(out_params)
  end


  private

  def out_params
    binding.pry
    params.require(:out).permit(:get_out, :go_home, :receipt_id, :return_id).marge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goouts_helper.rb
module GooutsHelper
end

app/helpers/outs_helper.rb
module OutsHelper
end

app/views/goouts/index.html.erb
<%= render "shared/header" %>



<%= link_to( outs_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>更新する</span>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Goout35711</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/outs/index.html.erb
<header>
    <h2 class='service-title'>
      点呼一覧
    </h2>
</header>

<div class='main'>
  <%= form_with model: prototype,  local: true do |f|%>
  <div class="field">
    <%= f.label :get_out, "プロトタイプの名称" %><br />
    <%= f.text_field :get_out, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :go_home, "キャッチコピー" %><br />
    <%= f.text_area :go_home, class: :form__text, id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :receipt_id, "コンセプト" %><br />
    <%= f.text_area :receipt_id, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :return_id, "プロトタイプの画像" %><br />
    <%= f.file_field :return_id, id:"prototype_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">点呼一覧</a></h1>

        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            <a class="post" href="/posts/new">投稿する</a>
          </div>

        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: 'post' %>
            <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
          </div>

        <% end %>
      </div>
</header>

app/views/shared/footer.html.erb
<footer class='fotter'>
  <div class='fotter-text'>